### ISSUE TITLE
Drop-down list doesn't closings on back button

### ISSUE THREAD

**Issue by AnnaShepa** [bugy/shop-list#100]
Android 4.0.4

Long tap on product at the main screen
Tap any field with drop-down list, e.g. units of measure
Press Back button

AR: drop-down list still opened over screens, even after switching to another screen
ER: drop-down list is closed

**Comment by bugy** [comment]
Same happens for categories filter even on newer Android versions

**Comment by bugy** [comment]
Spinner was fixed in a library.

Now both categories filter and spinner will just close on back button, and no other actions (e.g. moving to a previous screen) will be performed.
