### ISSUE TITLE
Change icons at the Menu

### ISSUE THREAD

**Issue by AnnaShepa** [bugy/shop-list#24]
Change icon for Products
Change icon for Categories (to the flag)

**Comment by bugy** [comment]
@AnnaShepa please provide icons (in 24dp size)

**Comment by AnnaShepa** [comment]
for Products one of this:
https://material.io/icons/#ic_local_dining
https://material.io/icons/#ic_local_pizza
https://material.io/icons/#ic_local_florist
or something here https://www.vecteezy.com/vector-art/104799-solid-fruit-vector-icons

**Comment by AnnaShepa** [comment]
for Categories https://material.io/icons/#ic_bookmark_border
