### ISSUE TITLE
Name of categories shouldn't be validate by dictionary

### ISSUE THREAD

**Issue by AnnaShepa** [bugy/shop-list#25]
1) Open Categories screen
2) Add some category with name not from dictionary

AR: there is red line under name
ER: no red line

**Comment by bugy** [comment]
Last fixed worked both on Galaxy Nexus (v22) and Nexus 5X (v24). 
Apparently the fix didn't work either on old versions or on custom ROM.
Made an another fix, hopefully this one will work
