### ISSUE TITLE
List of default products

### ISSUE THREAD

**Issue by bugy** [bugy/shop-list#48]
When a new user installs the ShopList, it would be helpful to provide the list of default products (at least 30 most popular) with a couple of example categories.
@AnnaShepa, could you provide the most common/popular product and categories names?

**Comment by AnnaShepa** [comment]
Apples
Bacon
Bananas 
Beans
Beer
Beef
Bread
Carrots
Cheese
Chips
Coffee
Cucumber
Eggs
Fish
Flour
Juice
Honey
Milk
Onion
Olive oil
Paper towel
Pfeffer 
Salt
Shampoo
Soap
Tea
Sugar

**Comment by AnnaShepa** [comment]
Яблоки 
Бекон
Бананы
Фасоль
Пиво
Говядина
Свинина
Хлеб
Морковь
Сыр
Творог
Кофе
Чай
Огурцы
Помидоры
Яйца
Рыба
Мука
Сахар 
Соль
Перец
Мед
Сок
Молоко
Лук
Масло оливковое
Масло подсолнечное
Масло сливочное
Туалетная бумага
Ватные диски
Мыло 
Шампунь

**Comment by bugy** [comment]
Categories feature future is not clear yet. For the moment we add only default products. Default categories should be done in a separate task (if should at all)
