### ISSUE TITLE
App crashes after regional settings changing 

### ISSUE THREAD

**Issue by AnnaShepa** [bugy/shop-list#65]
1) Set russian localisation on the phone 
2) Add some product to buy 
3) set some decimal count 
4) Change the localisation to English 
5) Tap on the product at the To Buy list 
6) Change count 
AR: app crashes 
ER: after the 4th step application should be opened with , instead of . as decimal symbol.

**Comment by bugy** [comment]
Unable to reproduce

**Comment by AnnaShepa** [comment]
crash doesn't reproduced, but after rerun with a new language settings decimal symbol schould be changed

**Comment by bugy** [comment]
Not so important. This is default Android behaviour and I think changing format only on application rerun (kill and run) is fine
