### ISSUE TITLE
Sometimes comment icon shows to way from the product

### ISSUE THREAD

**Issue by AnnaShepa** [bugy/shop-list#66]
1) Add some product with a short name 
2) Add some others products
3) Tap Add button at the main screen 
4) Fast scroll the list
 AR: comment icon is to way from short name

**Comment by AnnaShepa** [comment]
![screenshot_2017-01-02-13-02-47_net buggy shoplist](https://cloud.githubusercontent.com/assets/24183408/21588909/cb869ec4-d0eb-11e6-8d4a-9bd2b95968df.png)

**Comment by bugy** [comment]
We are removing this icon anyway
