### ISSUE TITLE
Add item panels stays visible after changing a screen

### ISSUE THREAD

**Issue by bugy** [bugy/shop-list#71]
Steps to reproduce:
1. Open application (to buy screen should be opened)
2. Open "Products" screen from menu
3. Open "To buy" screen from menu
4. Open "Products" screen from menu
Actual result: "Add item" field is remaining on top. Any sunsequential changes of the screen will keep this field.

**Comment by AnnaShepa** [comment]
Issue reproduces with the next steps:
Open Products screen
Open To Buy screen
Press Back button

**Comment by bugy** [comment]
This is different bug and please don't touch closed issues (if they were closed intentionally)

Moved the new issue in another ticket: https://github.com/bugy/shop-list/issues/104
