### ISSUE TITLE
Sending email, when app crashes

### ISSUE THREAD

**Issue by bugy** [bugy/shop-list#89]
Now, when app crashes, user can only reopen it. For making support easier, it should be possible to send current app state and error information to developers (me :) ).
Since there is no server available for the app, one of the easiest ways would be to send report via email. This should be optional, i.e. user can decide whether just to close the app or also send email with report
Report should be prefilled with important information, e.g.: stack trace, API version, screen dimensions, database version, etc.

**Comment by bugy** [comment]
In test version of an app, an exception can be triggered by clicking multiple (4) times on version in About app screen

**Comment by AnnaShepa** [comment]
Please, delete background on button pressing
